# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: sample
      POSTGRES_USER: sample
      POSTGRES_DB: home
    # Persist data sample
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  server:
    build:
      dockerfile: ./docker/backend.Dockerfile
      context: .
    image: golang:1.19.6
    container_name: server
    ports:
      - 8080:8080
    depends_on:
      - "db"